apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jamulus-helm.fullname" . }}
  labels:
    {{- include "jamulus-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jamulus-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jamulus-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jamulus-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "Jamulus" ]
          args:
            - "--server"
            - "--nogui"
            - "--port"
            - "{{ .Values.service.port }}"
            {{- if .Values.jamulus.centralServer }}
            - "--centralserver"
            - "{{ .Values.jamulus.centralServer }}"
            {{- end }}
            {{- if .Values.jamulus.serverInfo }}
            - "--serverinfo"
            - "{{ .Values.jamulus.serverInfo }}"
            {{- end }}
            {{- if .Values.jamulus.welcomeMessage }}
            - "--welcomemessage"
            - "{{ .Values.jamulus.welcomeMessage }}"
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jamulus
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
