apiVersion: v1
kind: Service
metadata:
  name: {{ include "jamulus-helm.fullname" . }}
  labels:
    {{- include "jamulus-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: jamulus
      protocol: UDP
      name: jamulus
  selector:
    {{- include "jamulus-helm.selectorLabels" . | nindent 4 }}
